permalink: /:categories/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

auto: true

pygments: true

production_url : http://pnts.github.com

paginate: 2

paginate_file: index.html
